### ISSUE TITLE
list multiple addresses from command line for generation genesis.json

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/mint-client#12]
additional options: passing in the pubkeys we want to use for validators, and maybe passing a csv file containing addresses to include in the genesis with their starting balance and permissions.

**Comment by compleatang** [comment]
:+1:

**Comment by zramsay** [comment]
had to remove several commits - latest develop branch wasn't building. Using pubkeys instead of addrs -> priv_validators generally won't be on the host...could mimic part of what `mintkey eris` does, I suppose.

**Comment by ebuchman** [comment]
https://github.com/eris-ltd/mint-client/pull/14
