### ISSUE TITLE
Failing to compile

### ISSUE THREAD

**Issue by hvram1** [eris-ltd/mint-client#44]
Hi
   I am trying to follow the README . I did a pull of the eris-cli

I executed the 
 go get github.com/eris-ltd/eris-keys
# github.com/eris-ltd/eris-keys/crypto/secp256k1
In file included from ./secp256k1/src/num.h:17:0,
                 from ./secp256k1/src/num_impl.h:14,
                 from ./secp256k1/src/secp256k1.c:12,
                 from goApps/src/github.com/eris-ltd/eris-keys/crypto/secp256k1/secp256.go:16:
./secp256k1/src/num_gmp.h:10:17: fatal error: gmp.h: No such file or directory
 #include <gmp.h>
                 ^
compilation terminated.

**Comment by compleatang** [comment]
`sudo apt-get install libgmp3-dev`

**Comment by hvram1** [comment]
This worked . Should I close the issue or will you update the documentation to include this ?

**Comment by compleatang** [comment]
@ebuchman added to README last night.
