### ISSUE TITLE
mintgen should be able to build random + add established pub keys

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/mint-client#45]
**Problem** -- I want to run 5 validator nodes on cloud droplets but I also want to give my own public key to the genesis block so that I have full permissions on the chain.

**Solution** -- Add a `--pub` flag to mintgen random for addition to the genesis block.

**Comment by ebuchman** [comment]
think we need an additional flag to tell what permissions to give the keys?

maybe --pub will take a list and will give the default perms, we can add a `root` flag to give it all the perms, otherwise a `--csv` flag to take an accounts.csv to add into the genesis

**Comment by compleatang** [comment]
i like the idea of separating those. so `mintgen random 5 --pub FOO --root BAR` gives $FOO default perms, $BAR all perms, and all the random default perms?

the perms flag gets at a related issue of how much precision should `random` support vis a vis `known` and csv's. Personally, I'd lean towards not adding a perms flag since random is supposed to be for quick offs. We can make the sequencing for assembling what's needed to be fed into `known` a bit stronger which would go further than a perms flag imo. But this opinion is not strongly held.

plus assembling csv's is sort of fun :)
