### ISSUE TITLE
Post 192.168.5.xxx:46657: unsupported protocol scheme ""

### ISSUE THREAD

**Issue by rguikers** [eris-ltd/mint-client#54]
```
mintinfo status
```

or any other mintinfo command results in error :

```
Post 192.168.5.xxx:46657: unsupported protocol scheme ""
```

Using the develop stream at this moment for setting permissions through mintx permission, this is working fine on latest eris-cli master.
Already set the env's for MINT, so configured fine (tested with mintx).

Any idea?, cannot find the exact error result in the code, and personally not a Go specialist..

Thanks,

Rob.

**Comment by compleatang** [comment]
Rob, we need to fix this but for now you just need to call it with an http:// before the IP Address.

**Comment by rguikers** [comment]
Thanks Casey for the really quick reply. Tested this, and working. Will use the forum for question about setting permissions without mintx, fi through erisdb.js.
Thanks,

**Comment by compleatang** [comment]
Great. Even better just to ask in the issues of the repo where the whole team has viz. You can also set permissions with eris-pm by the way. Assuming the chain is instantiated and the account changing the permissions has `root` permissions on the chain.

**Comment by rguikers** [comment]
Thanks, asked the question in erisdb.js repo..

**Comment by compleatang** [comment]
:rocket: :guitar:
