### ISSUE TITLE
mintx bond not working

### ISSUE THREAD

**Issue by dharmesh-kh24** [eris-ltd/mint-client#70]
I am trying bonding/unbonding tutorial following [this](https://github.com/eris-ltd/eris-cm/blob/master/docs/examples/bond-unbond.md). I am able to _Send tokens from validator to new account_ using `mintx send`. Now next step is to _Send a bond tx from new account_ using mintx bond.
I am trying this command:

`mintx bond --amt 150000 --pubkey 3C82AF03B07F470F4C74B21A618D92972D009417259ADC92C36FD405DCBD2F30 --to 6C3DCEE7BB448E8A53A86547A6D6AED505CC205A --chainID bonding --node-addr=localhost:56657 --sign-addr=localhost:4767 --sign --broadcast`

It is giving error:

`Expected string but got type []interface {}`

**Comment by zramsay** [comment]
Hi @dharmesh-kh24, unfortunately this repo is deprecated. It has been moved to `eris-client` within https://github.com/eris-ltd/eris-db. Note also that bonding/unbonding has been disabled for the time being and will be re-implemented in a future release. If you really want to access its functionality, you'll need to stick with release version 0.11.4 but it'll be limiting
